import { Poppins } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "@/context";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "ROCA - Documents Upload",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ContextProvider>
        <body className={poppins.className}>{children}</body>
      </ContextProvider>
    </html>
  );
}
